### ISSUE TITLE
SPI compilation errors set

### ISSUE THREAD

**Issue by markusthegeek** [JacobChrist/HackadayS8-OscilliscopeArt#1]
Hey @JacobChrist nice to meet you at the Hackaday conference. I soldered your board and am know trying to install the software.

Note that with the official Raspberry Pi Pico Arduino IDE board package "Arduino Mbed OS RP2040 Boards" you get compilation errors with SPI methods like setRX not found.

Looks like you have to install a custom library from here instead:
https://arduino-pico.readthedocs.io/en/latest/install.html#installing-via-arduino-boards-manager

Maybe you could add that to your readme? 

gruss, 
Markus

**Comment by markusthegeek** [comment]
Should also mention that the badge cannot be directly programmed with Arduino IDE but boots into MicroPython. In order to program needs to press button, then connect to USB, then release button.

After flashing a couple of times, I believe now the firmware got replaced and it is now automatically doing the drive mode during upload.

**Comment by markusthegeek** [comment]
Also a hint to use the sip header code branch would be nice, I spent quit some time wondering if the pins selected in the master branch code were correct...

**Comment by JacobChrist** [comment]
Yes yes, all correct, its second nature to me to use the Earle Philhower library for the Pi Pico.  Didn't even realize the badges were using MicroPython.  

https://github.com/earlephilhower/arduino-pico

Did you get it to work?

Jacob

**Comment by JacobChrist** [comment]
I added your suggestions to the readme.md (on the master branch) and in the Hackaday.io page.  Can you review and comment if the issue can be closed?

**Comment by markusthegeek** [comment]
Thanks, Jacob, readme is looking great 😄 yes I got it to work in the end yesterday, thanks again for all your work and free PCBs!
